services:
  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network

  redis:
    image: redis:8
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mern_network

  backend:
    build:
      context: ./chatapp-socket
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatapp
      - JWT_SECRET=supersecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mern_network

  frontend:
    build:
      context: ./chat-app-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - mern_network

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge
